### ISSUE TITLE
No backup fonts in style.css

### ISSUE THREAD

**Issue by paultela** [CWDG/web-calc#2]
You should have a fall back font specified other than Helvetica for users who don't have that installed.  Anyone want to work on a PR for this?

**Comment by arcdigital** [comment]
@Hardolaf you wanna take charge of this?

**Comment by Hardolaf** [comment]
It's in PR #3

**Comment by arcdigital** [comment]
Fixed by @Hardolaf in #3. Closing.

**Comment by paultela** [comment]
:shipit:
