### ISSUE TITLE
Helvetica is cliche

### ISSUE THREAD

**Issue by mikeletscher** [CWDG/web-calc#5]
It makes me feel bored. I don't want to feel bored. I would rather it be Open Sans. Thoughts?

**Comment by paultela** [comment]
+1

**Comment by arcdigital** [comment]
Sure. Go ahead.

**Comment by paultela** [comment]
@Hardolaf can you take care of this? Thanks in advance

**Comment by mikeletscher** [comment]
+1

**Comment by Hardolaf** [comment]
Open Sans is not web safe, should I have Comic Sans as fallback?

**Comment by paultela** [comment]
Good call

**Comment by arcdigital** [comment]
+1

**Comment by mikeletscher** [comment]
Google fonts, with comic sans fallback

**Comment by arcdigital** [comment]
No google fonts.

**Comment by mikeletscher** [comment]
:-1:
