### ISSUE TITLE
No submit button

### ISSUE THREAD

**Issue by mikeletscher** [CWDG/web-calc#7]
What if Javascript is disabled?

**Comment by Hardolaf** [comment]
Can someone fix this for NoScript users? @arcdigital ?

**Comment by mikeletscher** [comment]
+4

**Comment by paultela** [comment]
Isn't this a javascript calculator?

**Comment by mikeletscher** [comment]
Aren't you a javascript calculator?

**Comment by paultela** [comment]
Touché

**Comment by mikeletscher** [comment]
It's not acceptable to have Javascript disabled anymore.
